In [1]:
import tensorflow as tf
from tensorflow.keras.datasets import boston_housing
from sklearn import preprocessing


In [2]:
(train_x, train_y),(test_x, test_y) = boston_housing.load_data()

57026/57026 [==============================] - 0s 0us/step


In [3]:
print("train shape : ", train_x.shape)
print("test shape : ", test_x.shape)
print("Actual train output : ", train_y.shape)
print("Actual test outpput : ", test_y.shape)


train shape :  (404, 13)
test shape :  (102, 13)
Actual train output :  (404,)
Actual test outpput :  (102,)


In [4]:
train_x[0]

array([  1.23247,   0.     ,   8.14   ,   0.     ,   0.538  ,   6.142  ,
        91.7    ,   3.9769 ,   4.     , 307.     ,  21.     , 396.9    ,
        18.72   ])

In [5]:
train_y[0]

15.2

In [7]:
train_x=preprocessing.normalize(train_x)
test_x=preprocessing.normalize(test_x)

In [8]:
train_x[0]

array([0.0024119 , 0.        , 0.01592969, 0.        , 0.00105285,
       0.01201967, 0.17945359, 0.00778265, 0.00782786, 0.6007879 ,
       0.04109624, 0.77671895, 0.03663436])

In [9]:
train_y[0]

15.2

In [15]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import *

def H_P_model():
    model = Sequential()
    model.add(Dense(128, activation = 'relu', input_shape = (train_x[0].shape)))
    model.add(Dense(64, activation = 'relu'))
    model.add(Dense(32, activation = 'relu'))
    model.add(Dense(1))
    model.compile(optimizer = 'rmsprop', loss = 'mse', metrics = ['mae'])
    return model

In [16]:
import numpy as np
k =4
num_val_samples = len(train_x)
num_epochs = 100
all_scores = []


In [28]:
model = H_P_model()
model.fit(x = train_x, y = train_y, epochs = num_epochs, batch_size =1, verbose = 1, validation_data = (test_x, test_y) )

Epoch 1/100
404/404 [==============================] - 1s 2ms/step - loss: 121.5071 - mae: 7.7081 - val_loss: 74.8664 - val_mae: 6.1237
Epoch 2/100
404/404 [==============================] - 1s 2ms/step - loss: 64.7717 - mae: 5.6118 - val_loss: 59.6368 - val_mae: 5.5855
Epoch 3/100
404/404 [==============================] - 1s 1ms/step - loss: 62.8999 - mae: 5.4627 - val_loss: 56.6696 - val_mae: 5.4813
Epoch 4/100
404/404 [==============================] - 1s 1ms/step - loss: 60.2769 - mae: 5.2780 - val_loss: 53.8298 - val_mae: 5.3790
Epoch 5/100
404/404 [==============================] - 1s 1ms/step - loss: 57.5506 - mae: 5.1656 - val_loss: 53.6250 - val_mae: 5.2882
Epoch 6/100
404/404 [==============================] - 1s 1ms/step - loss: 55.2119 - mae: 5.0612 - val_loss: 58.1687 - val_mae: 5.3623
Epoch 7/100
404/404 [==============================] - 1s 2ms/step - loss: 52.8381 - mae: 4.9732 - val_loss: 54.3866 - val_mae: 5.6656
Epoch 8/100
404/404 [==============================] -

In [29]:
from sklearn.metrics import mean_squared_error, confusion_matrix, accuracy_score


In [30]:
y_pred = model.predict(test_x).flatten()

4/4 [==============================] - 0s 2ms/step


In [31]:
# Calculate Mean Squared Error (MSE)
mse = mean_squared_error(test_y, y_pred)
print("Mean Squared Error (MSE):", mse)

Mean Squared Error (MSE): 32.400195922632655


In [32]:
# Convert predictions to binary values (0 or 1) for classification
binary_pred = np.where(y_pred >= np.mean(y_pred), 1, 0)
binary_test = np.where(test_y >= np.mean(test_y), 1, 0)

In [33]:
# Calculate Confusion Matrix
cm = confusion_matrix(binary_test, binary_pred)
print("Confusion Matrix:")
print(cm)

Confusion Matrix:
[[52  6]
 [12 32]]


In [34]:
# Calculate Accuracy
accuracy = accuracy_score(binary_test, binary_pred)
print("Accuracy:", accuracy)

Accuracy: 0.8235294117647058
